number_of_detectors: 1

# indexing from 0, 0..number_of_detectors
Sensor_0:

  # by this name the device is found, run "rosrun rospix list_devices to see it"
  name: 'Medipix2 ver 1.32 sn: 1096'

  # this is how it will be named in ros
  custom_name: 'lite'
  equalization: '/home/klaxalk/equalizace.txt'
  
  defaults:
    threshold: 300
    bias: 10.0  # [Volt]
    exposure: 1.0 # [second]
    mode: 1 # [0 = MPX, 1 = TOT]

    # dacs can be found in calibration protocol (or equalization protocol)
    dacs: [1,100,255,127,127,0,300,7,130,128,80,85,128,128]
