number_of_detectors: 2

# indexing from 0, 0..number_of_detectors
Sensor_0:

  # by this name the device is found, run "rosrun rospix list_devices to see it"
  name: 'Medipix2 ver 1.32 sn: 1096'

  # this is how it will be named in ros
  custom_name: 'lite'
  equalization: '/home/odroid/equalisation.bpc'
  
  defaults:
    threshold: 340
    bias: 10.0  # [Volt]
    exposure: 1.0 # [second]
    mode: 1 # [0 = MPX, 1 = TOT]

    # dacs can be found in calibration protocol (or equalization protocol)
    dacs: [1,100,255,127,127,0,350,7,130,128,80,85,128,128]

Sensor_1:

  name: 'dummy'

  # should we simulate optics?
  simulate_focus: true

  # optics dimensionality 1=1D, 2=2D
  optics_dimension: 2

  photon_flux: 100       # [photons/s], whole number

  # should we simulation radiation background?
  simulate_background: true

  # how many images of radiation background do we have?
  n_images: 20

  defaults:

    exposure: 1.0 # [second]

