number_of_detectors: 2

# indexing from 0, 0..number_of_detectors
sensor_0:

  # by this name the device is found, run "rosrun rospix list_devices to see it"
  name: 'Medipix2 ver 1.32 sn: 1096'

  # location of the equalization file
  equalization: 'lite_rigaku.bpc' # *.bpc is needed
  
  defaults:
    threshold: 340
    bias: 10.0  # [Volt]
    exposure: 1.0 # [second]
    mode: 1 # [0 = MPX, 1 = TOT]

    # dacs can be found in calibration protocol (or equalization protocol)
    dacs: [1,100,255,127,127,0,350,7,130,128,80,85,128,128]

sensor_1:

  name: 'dummy'

  simulate_focus: true        # should we simulate optics?
  optics_dimension: 2         # optics dimensionality 1=1D, 2=2D
  photon_flux: 100            # [photons/s], whole number
  simulate_background: true   # should we simulation radiation background?
  n_images: 20                # how many images of radiation background do we have?

  defaults:
    exposure: 1.0             # [seconds]
